<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class CatalogSeeder extends Seeder
{
    public function run(): void
    {
        Product::query()->delete();
        Category::query()->delete();

        $lunchBox = Category::query()->create([
            'slug' => 'lunch-box',
            'name' => 'Lunch Box',
            'description' => 'Lunch boxes and meal carriers for school, office, and everyday travel.',
            'image' => '/products/lunch-box/everyday-lunchbox-set/01.jpg',
            'featured' => true,
            'sort_order' => 1,
        ]);

        $toys = Category::query()->create([
            'slug' => 'toys',
            'name' => 'Toys',
            'description' => 'Creative play picks for kids — blocks, kitchen sets, plush, and more.',
            'image' => '/products/toys/wooden-building-blocks/01.jpg',
            'featured' => true,
            'sort_order' => 2,
        ]);

        foreach ($this->products() as $product) {
            Product::query()->create([
                ...$product,
                'category_id' => $lunchBox->id,
            ]);
        }

        foreach ($this->toyProducts() as $product) {
            Product::query()->create([
                ...$product,
                'category_id' => $toys->id,
            ]);
        }
    }

    private function products(): array
    {
        return [
            [
                'external_id' => 'lb-5',
                'slug' => 'everyday-lunch-box-set',
                'name' => 'Everyday Lunch Box Set',
                'sku' => 'LB-0005',
                'price' => 899,
                'compare_at_price' => 1299,
                'rating' => 0,
                'reviews' => 0,
                'image' => '/products/lunch-box/everyday-lunchbox-set/01.jpg',
                'hover_image' => '/products/lunch-box/everyday-lunchbox-set/02.jpg',
                'badge' => 'Sale',
                'tags' => ['daily-use', 'featured', 'set'],
                'description' => 'Compact lunch box set with matching pieces for school, office, and daily meals.',
                'details' => [
                    'Practical lunch storage for school, office, and travel',
                    'Compact matching set for everyday meals',
                    'Save ₹400 compared with MRP',
                    '7-day replacement for damaged or incorrect lunch boxes',
                ],
                'stock' => 28,
                'variant_group_id' => null,
                'color_name' => null,
                'color_hex' => null,
                'gallery' => $this->gallery('everyday-lunchbox-set', 13),
            ],
            [
                'external_id' => 'lb-6',
                'slug' => 'tokyo-3-compartment-steel-lunch-box-blue',
                'name' => 'Tokyo 3 Compartment Steel Lunch Box - Blue',
                'sku' => 'LB-0006',
                'price' => 1199,
                'compare_at_price' => 1699,
                'rating' => 0,
                'reviews' => 0,
                'image' => '/products/lunch-box/tokyo-steel-lunch-box-blue/05.jpg',
                'hover_image' => '/products/lunch-box/tokyo-steel-lunch-box-blue/07.jpg',
                'badge' => 'Featured',
                'tags' => ['steel', 'featured'],
                'description' => 'Blue three-compartment steel lunch box designed for neat portions and easy carrying.',
                'details' => [
                    'Three-compartment steel layout',
                    'Color: Blue',
                    'Save ₹500 compared with MRP',
                    'Food-safe packing and delivery in 2-5 days',
                ],
                'stock' => 22,
                'variant_group_id' => 'tokyo-3-compartment-steel-lunch-box',
                'color_name' => 'Blue',
                'color_hex' => '#3f82d7',
                'gallery' => $this->gallery('tokyo-steel-lunch-box-blue', 12),
            ],
            [
                'external_id' => 'lb-7',
                'slug' => 'tokyo-3-compartment-steel-lunch-box-green',
                'name' => 'Tokyo 3 Compartment Steel Lunch Box - Green',
                'sku' => 'LB-0007',
                'price' => 1199,
                'compare_at_price' => 1699,
                'rating' => 0,
                'reviews' => 0,
                'image' => '/products/lunch-box/tokyo-steel-lunch-box-green/01.jpg',
                'hover_image' => '/products/lunch-box/tokyo-steel-lunch-box-green/02.jpg',
                'badge' => null,
                'tags' => ['steel'],
                'description' => 'Green three-compartment steel lunch box with a practical layout for balanced meals.',
                'details' => [
                    'Three-compartment steel layout',
                    'Color: Green',
                    'Save ₹500 compared with MRP',
                    '7-day replacement for damaged or incorrect lunch boxes',
                ],
                'stock' => 18,
                'variant_group_id' => 'tokyo-3-compartment-steel-lunch-box',
                'color_name' => 'Green',
                'color_hex' => '#64a85f',
                'gallery' => $this->gallery('tokyo-steel-lunch-box-green', 5),
            ],
            [
                'external_id' => 'lb-8',
                'slug' => 'tokyo-3-compartment-steel-lunch-box-pink',
                'name' => 'Tokyo 3 Compartment Steel Lunch Box - Pink',
                'sku' => 'LB-0008',
                'price' => 1199,
                'compare_at_price' => 1699,
                'rating' => 0,
                'reviews' => 0,
                'image' => '/products/lunch-box/tokyo-steel-lunch-box-pink/01.jpg',
                'hover_image' => '/products/lunch-box/tokyo-steel-lunch-box-pink/02.jpg',
                'badge' => null,
                'tags' => ['steel'],
                'description' => 'Pink three-compartment steel lunch box for tidy homemade meals and snacks.',
                'details' => [
                    'Three-compartment steel layout',
                    'Color: Pink',
                    'Save ₹500 compared with MRP',
                    'Food-safe packing and delivery in 2-5 days',
                ],
                'stock' => 16,
                'variant_group_id' => 'tokyo-3-compartment-steel-lunch-box',
                'color_name' => 'Pink',
                'color_hex' => '#f09bb9',
                'gallery' => $this->gallery('tokyo-steel-lunch-box-pink', 5),
            ],
            [
                'external_id' => 'lb-9',
                'slug' => 'bear-family-lunch-box',
                'name' => 'Bear Family Lunch Box',
                'sku' => 'LB-0009',
                'price' => 749,
                'compare_at_price' => 1099,
                'rating' => 0,
                'reviews' => 0,
                'image' => '/products/lunch-box/bear-family-lunch-box/01.jpg',
                'hover_image' => '/products/lunch-box/bear-family-lunch-box/02.jpg',
                'badge' => 'Featured',
                'tags' => ['kids', 'featured'],
                'description' => "Bear-themed lunch box with a cheerful look for kids' meals, snacks, and school bags.",
                'details' => [
                    'Cute bear-themed kids design',
                    'Ideal for school bags and snacks',
                    'Save ₹350 compared with MRP',
                    '7-day replacement for damaged or incorrect lunch boxes',
                ],
                'stock' => 34,
                'variant_group_id' => null,
                'color_name' => null,
                'color_hex' => null,
                'gallery' => $this->gallery('bear-family-lunch-box', 16),
            ],
            [
                'external_id' => 'lb-10',
                'slug' => 'delicious-steel-lunch-box',
                'name' => 'Delicious Steel Lunch Box',
                'sku' => 'LB-0010',
                'price' => 999,
                'compare_at_price' => 1499,
                'rating' => 0,
                'reviews' => 0,
                'image' => '/products/lunch-box/delicious-steel-lunch-box/01.jpg',
                'hover_image' => '/products/lunch-box/delicious-steel-lunch-box/13.jpg',
                'badge' => 'Sale',
                'tags' => ['steel', 'featured'],
                'description' => 'Steel lunch box built for everyday tiffin packing with a clean, durable finish.',
                'details' => [
                    'Durable steel body for daily tiffin use',
                    'Clean, practical finish',
                    'Save ₹500 compared with MRP',
                    'Food-safe packing and delivery in 2-5 days',
                ],
                'stock' => 20,
                'variant_group_id' => null,
                'color_name' => null,
                'color_hex' => null,
                'gallery' => $this->gallery('delicious-steel-lunch-box', 15),
            ],
            [
                'external_id' => 'lb-11',
                'slug' => 'koi-koi-steel-lunch-box-blue',
                'name' => 'Koi-Koi Steel Lunch Box - Blue',
                'sku' => 'LB-0011',
                'price' => 1199,
                'compare_at_price' => 1699,
                'rating' => 0,
                'reviews' => 0,
                'image' => '/products/lunch-box/hero-showcase/koi-koi-steel-lunch-box-blue.jpeg',
                'hover_image' => '/products/lunch-box/koi-koi-steel-lunch-box-blue/01.jpg',
                'badge' => 'Featured',
                'tags' => ['steel', 'featured'],
                'description' => 'Three-compartment steel lunch box with leak-proof clips, a separate soup container, and a clear lid for easy packing.',
                'details' => [
                    'Leak-proof clips with clear lid',
                    'Separate soup container included',
                    'Color: Blue',
                    'Save ₹500 compared with MRP',
                ],
                'stock' => 15,
                'variant_group_id' => 'koi-koi-steel-lunch-box',
                'color_name' => 'Blue',
                'color_hex' => '#9ec5e8',
                'gallery' => $this->withHero(
                    '/products/lunch-box/hero-showcase/koi-koi-steel-lunch-box-blue.jpeg',
                    $this->gallery('koi-koi-steel-lunch-box-blue', 9)
                ),
            ],
            [
                'external_id' => 'lb-12',
                'slug' => 'koi-koi-steel-lunch-box-pink',
                'name' => 'Koi-Koi Steel Lunch Box - Pink',
                'sku' => 'LB-0012',
                'price' => 1199,
                'compare_at_price' => 1699,
                'rating' => 0,
                'reviews' => 0,
                'image' => '/products/lunch-box/koi-koi-steel-lunch-box-pink/01.jpg',
                'hover_image' => null,
                'badge' => null,
                'tags' => ['steel'],
                'description' => 'Pink three-compartment steel lunch box with leak-proof clips, a separate soup container, and a clear lid for everyday meals.',
                'details' => [
                    'Leak-proof clips with clear lid',
                    'Separate soup container included',
                    'Color: Pink',
                    'Save ₹500 compared with MRP',
                ],
                'stock' => 14,
                'variant_group_id' => 'koi-koi-steel-lunch-box',
                'color_name' => 'Pink',
                'color_hex' => '#f4c4d0',
                'gallery' => $this->gallery('koi-koi-steel-lunch-box-pink', 1),
            ],
            [
                'external_id' => 'lb-13',
                'slug' => 'koi-koi-steel-lunch-box-purple',
                'name' => 'Koi-Koi Steel Lunch Box - Purple',
                'sku' => 'LB-0013',
                'price' => 1199,
                'compare_at_price' => 1699,
                'rating' => 0,
                'reviews' => 0,
                'image' => '/products/lunch-box/koi-koi-steel-lunch-box-purple/01.jpg',
                'hover_image' => null,
                'badge' => null,
                'tags' => ['steel'],
                'description' => 'Purple three-compartment steel lunch box with leak-proof clips, a separate soup container, and a clear lid for balanced tiffin packing.',
                'details' => [
                    'Leak-proof clips with clear lid',
                    'Separate soup container included',
                    'Color: Purple',
                    'Save ₹500 compared with MRP',
                ],
                'stock' => 12,
                'variant_group_id' => 'koi-koi-steel-lunch-box',
                'color_name' => 'Purple',
                'color_hex' => '#c4b0dc',
                'gallery' => $this->gallery('koi-koi-steel-lunch-box-purple', 1),
            ],
            [
                'external_id' => 'lb-14',
                'slug' => 'printed-steel-lunch-box-blue',
                'name' => 'Printed Steel Lunch Box - Blue',
                'sku' => 'LB-0014',
                'price' => 999,
                'compare_at_price' => 1499,
                'rating' => 0,
                'reviews' => 0,
                'image' => '/products/lunch-box/printed-steel-lunch-box-blue/01.jpg',
                'hover_image' => '/products/lunch-box/printed-steel-lunch-box-blue/02.jpg',
                'badge' => null,
                'tags' => ['steel', 'printed'],
                'description' => 'Teal printed steel lunch box with a playful food-themed lid, four-side locks, and a stainless steel interior for school and office meals.',
                'details' => [
                    'Printed food-themed lid',
                    'Four-side locking clips',
                    'Color: Blue',
                    'Save ₹500 compared with MRP',
                ],
                'stock' => 19,
                'variant_group_id' => 'printed-steel-lunch-box',
                'color_name' => 'Blue',
                'color_hex' => '#4db8b0',
                'gallery' => $this->gallery('printed-steel-lunch-box-blue', 4),
            ],
            [
                'external_id' => 'lb-15',
                'slug' => 'printed-steel-lunch-box-pink',
                'name' => 'Printed Steel Lunch Box - Pink',
                'sku' => 'LB-0015',
                'price' => 999,
                'compare_at_price' => 1499,
                'rating' => 0,
                'reviews' => 0,
                'image' => '/products/lunch-box/printed-steel-lunch-box-pink/01.jpg',
                'hover_image' => '/products/lunch-box/printed-steel-lunch-box-pink/02.jpg',
                'badge' => null,
                'tags' => ['steel', 'printed'],
                'description' => 'Pink printed steel lunch box with a colorful food-themed lid, secure side locks, and a stainless steel interior for daily tiffin use.',
                'details' => [
                    'Printed food-themed lid',
                    'Secure side locks',
                    'Color: Pink',
                    'Save ₹500 compared with MRP',
                ],
                'stock' => 17,
                'variant_group_id' => 'printed-steel-lunch-box',
                'color_name' => 'Pink',
                'color_hex' => '#f0a8c0',
                'gallery' => $this->gallery('printed-steel-lunch-box-pink', 3),
            ],
            [
                'external_id' => 'lb-16',
                'slug' => 'printed-steel-lunch-box-purple',
                'name' => 'Printed Steel Lunch Box - Purple',
                'sku' => 'LB-0016',
                'price' => 999,
                'compare_at_price' => 1499,
                'rating' => 0,
                'reviews' => 0,
                'image' => '/products/lunch-box/hero-showcase/printed-steel-lunch-box-purple.jpeg',
                'hover_image' => '/products/lunch-box/printed-steel-lunch-box-purple/01.jpg',
                'badge' => 'Sale',
                'tags' => ['steel', 'printed', 'featured'],
                'description' => 'Purple printed steel lunch box with a fun food-themed lid, four-side locking clips, and a stainless steel interior for neat meal packing.',
                'details' => [
                    'Printed food-themed lid',
                    'Four-side locking clips',
                    'Color: Purple',
                    'Save ₹500 compared with MRP',
                ],
                'stock' => 15,
                'variant_group_id' => 'printed-steel-lunch-box',
                'color_name' => 'Purple',
                'color_hex' => '#a898d8',
                'gallery' => $this->withHero(
                    '/products/lunch-box/hero-showcase/printed-steel-lunch-box-purple.jpeg',
                    $this->gallery('printed-steel-lunch-box-purple', 4)
                ),
            ],
            [
                'external_id' => 'lb-17',
                'slug' => 'safari-kids-steel-lunch-box-dino-green',
                'name' => 'Safari Kids Steel Lunch Box - Dino Green',
                'sku' => 'LB-0017',
                'price' => 899,
                'compare_at_price' => 1299,
                'rating' => 0,
                'reviews' => 0,
                'image' => '/products/lunch-box/safari-lunch-box-dino-green/01.jpg',
                'hover_image' => '/products/lunch-box/safari-lunch-box-dino-green/02.jpg',
                'badge' => 'Featured',
                'tags' => ['kids', 'steel', 'featured'],
                'description' => 'Super Dino Saur steel lunch box with a teal character lid, three-compartment steel tray, and four-side locks for school lunches.',
                'details' => [
                    'Character lid with steel tray',
                    'Four-side locks for school use',
                    'Color: Dino Green',
                    'Save ₹400 compared with MRP',
                ],
                'stock' => 26,
                'variant_group_id' => 'safari-kids-steel-lunch-box',
                'color_name' => 'Dino Green',
                'color_hex' => '#5eb8a8',
                'gallery' => $this->gallery('safari-lunch-box-dino-green', 3),
            ],
            [
                'external_id' => 'lb-18',
                'slug' => 'safari-kids-steel-lunch-box-dino-yellow',
                'name' => 'Safari Kids Steel Lunch Box - Dino Yellow',
                'sku' => 'LB-0018',
                'price' => 899,
                'compare_at_price' => 1299,
                'rating' => 0,
                'reviews' => 0,
                'image' => '/products/lunch-box/safari-lunch-box-dino-yellow/01.jpg',
                'hover_image' => '/products/lunch-box/safari-lunch-box-dino-yellow/02.jpg',
                'badge' => null,
                'tags' => ['kids', 'steel'],
                'description' => 'Yellow Super Dinosaur steel lunch box with a playful dino lid, stainless steel compartments, and secure side locks for kids on the go.',
                'details' => [
                    'Playful dino character lid',
                    'Stainless steel compartments',
                    'Color: Dino Yellow',
                    'Save ₹400 compared with MRP',
                ],
                'stock' => 24,
                'variant_group_id' => 'safari-kids-steel-lunch-box',
                'color_name' => 'Dino Yellow',
                'color_hex' => '#f5c842',
                'gallery' => $this->gallery('safari-lunch-box-dino-yellow', 3),
            ],
            [
                'external_id' => 'lb-19',
                'slug' => 'safari-kids-steel-lunch-box-chick-orange',
                'name' => 'Safari Kids Steel Lunch Box - Chick Orange',
                'sku' => 'LB-0019',
                'price' => 899,
                'compare_at_price' => 1299,
                'rating' => 0,
                'reviews' => 0,
                'image' => '/products/lunch-box/safari-lunch-box-chick-orange/01.jpg',
                'hover_image' => '/products/lunch-box/safari-lunch-box-chick-orange/02.jpg',
                'badge' => null,
                'tags' => ['kids', 'steel'],
                'description' => 'Super Bite Buddy chick steel lunch box with an orange character lid, steel interior tray, and leak-resistant locks for school tiffins.',
                'details' => [
                    'Chick character lid',
                    'Leak-resistant side locks',
                    'Color: Chick Orange',
                    'Save ₹400 compared with MRP',
                ],
                'stock' => 21,
                'variant_group_id' => 'safari-kids-steel-lunch-box',
                'color_name' => 'Chick Orange',
                'color_hex' => '#f5924e',
                'gallery' => $this->gallery('safari-lunch-box-chick-orange', 2),
            ],
            [
                'external_id' => 'lb-20',
                'slug' => 'safari-kids-steel-lunch-box-owl-purple',
                'name' => 'Safari Kids Steel Lunch Box - Owl Purple',
                'sku' => 'LB-0020',
                'price' => 899,
                'compare_at_price' => 1299,
                'rating' => 0,
                'reviews' => 0,
                'image' => '/products/lunch-box/hero-showcase/safari-lunch-box-owl-purple.png',
                'hover_image' => '/products/lunch-box/safari-lunch-box-owl-purple/01.jpg',
                'badge' => 'Sale',
                'tags' => ['kids', 'steel', 'featured'],
                'description' => 'Super Chickey owl steel lunch box with a purple character lid, three-compartment steel tray, and four-side locks for everyday school use.',
                'details' => [
                    'Owl character lid',
                    'Three-compartment steel tray',
                    'Color: Owl Purple',
                    'Save ₹400 compared with MRP',
                ],
                'stock' => 18,
                'variant_group_id' => 'safari-kids-steel-lunch-box',
                'color_name' => 'Owl Purple',
                'color_hex' => '#c4a8e8',
                'gallery' => $this->withHero(
                    '/products/lunch-box/hero-showcase/safari-lunch-box-owl-purple.png',
                    $this->gallery('safari-lunch-box-owl-purple', 2)
                ),
            ],
        ];
    }

    private function toyProducts(): array
    {
        return [
            [
                'external_id' => 'ty-1',
                'slug' => 'wooden-building-blocks',
                'name' => 'Wooden Building Blocks',
                'sku' => 'TY-0001',
                'price' => 799,
                'compare_at_price' => 1099,
                'rating' => 0,
                'reviews' => 0,
                'image' => '/products/toys/wooden-building-blocks/01.jpg',
                'hover_image' => null,
                'badge' => 'Featured',
                'tags' => ['creative', 'featured', 'sale'],
                'description' => 'Classic wooden blocks for open-ended building, stacking, and imaginative play.',
                'details' => [
                    'Smooth, kid-safe wooden pieces',
                    'Encourages creativity and motor skills',
                    'Save ₹300 compared with MRP',
                    'Food-safe packing and delivery in 2-5 days',
                ],
                'stock' => 36,
                'variant_group_id' => null,
                'color_name' => null,
                'color_hex' => null,
                'gallery' => ['/products/toys/wooden-building-blocks/01.jpg'],
            ],
            [
                'external_id' => 'ty-2',
                'slug' => 'mini-kitchen-play-set',
                'name' => 'Mini Kitchen Play Set',
                'sku' => 'TY-0002',
                'price' => 1499,
                'compare_at_price' => 1999,
                'rating' => 0,
                'reviews' => 0,
                'image' => '/products/toys/mini-kitchen-play-set/01.jpg',
                'hover_image' => null,
                'badge' => 'Sale',
                'tags' => ['pretend-play', 'featured', 'sale'],
                'description' => 'A cheerful pretend kitchen set for little chefs to cook up everyday adventures.',
                'details' => [
                    'Role-play kitchen for toddlers and kids',
                    'Durable pieces for daily play',
                    'Save ₹500 compared with MRP',
                    '7-day replacement for damaged or incorrect items',
                ],
                'stock' => 22,
                'variant_group_id' => null,
                'color_name' => null,
                'color_hex' => null,
                'gallery' => ['/products/toys/mini-kitchen-play-set/01.jpg'],
            ],
            [
                'external_id' => 'ty-3',
                'slug' => 'soft-plush-buddy',
                'name' => 'Soft Plush Buddy',
                'sku' => 'TY-0003',
                'price' => 599,
                'compare_at_price' => 899,
                'rating' => 0,
                'reviews' => 0,
                'image' => '/products/toys/soft-plush-buddy/01.jpg',
                'hover_image' => null,
                'badge' => 'Featured',
                'tags' => ['plush', 'featured', 'sale'],
                'description' => 'A soft, huggable plush companion for nap time, travel, and everyday cuddles.',
                'details' => [
                    'Ultra-soft plush finish',
                    'Perfect gift for little ones',
                    'Save ₹300 compared with MRP',
                    'Food-safe packing and delivery in 2-5 days',
                ],
                'stock' => 48,
                'variant_group_id' => null,
                'color_name' => null,
                'color_hex' => null,
                'gallery' => ['/products/toys/soft-plush-buddy/01.jpg'],
            ],
            [
                'external_id' => 'ty-4',
                'slug' => 'color-pattern-tiles',
                'name' => 'Color Pattern Tiles',
                'sku' => 'TY-0004',
                'price' => 699,
                'compare_at_price' => 999,
                'rating' => 0,
                'reviews' => 0,
                'image' => '/products/toys/color-pattern-tiles/01.jpg',
                'hover_image' => null,
                'badge' => 'Sale',
                'tags' => ['learning', 'featured', 'sale'],
                'description' => 'Bright pattern tiles that turn learning shapes and colors into hands-on fun.',
                'details' => [
                    'Colorful tiles for matching and patterns',
                    'Builds early learning skills',
                    'Save ₹300 compared with MRP',
                    '7-day replacement for damaged or incorrect items',
                ],
                'stock' => 40,
                'variant_group_id' => null,
                'color_name' => null,
                'color_hex' => null,
                'gallery' => ['/products/toys/color-pattern-tiles/01.jpg'],
            ],
        ];
    }

    private function gallery(string $folder, int $count): array
    {
        $images = [];

        for ($index = 1; $index <= $count; $index++) {
            $images[] = sprintf('/products/lunch-box/%s/%02d.jpg', $folder, $index);
        }

        return $images;
    }

    private function withHero(string $hero, array $gallery): array
    {
        return array_values(array_unique(array_merge([$hero], $gallery)));
    }
}
