export const brandAssets = {
  logo: '/images/ventures-mart-logo.png',
  logoLight: '/images/ventures-mart-logo-light.png',
  heroOne: '/images/home5-slideshow1.jpg',
  heroTwo: '/images/home5-slideshow2.jpg',
  heroThree: '/images/home5-slideshow3.jpg',
  heroHome: '/products/lunch-box/delicious-steel-lunch-box/13.jpg',
  heroVideo: '/images/hero/hero-loop.mp4',
  heroVideoMobile: '/images/hero/hero-loop-mobile.mp4',
  heroVideoTablet: '/images/hero/hero-loop-tablet.mp4',
  heroPoster: '/images/hero/poster.jpg',
  heroSlidesMobileTablet: [
    '/images/hero/lunch-1.webp',
    '/images/hero/lunch-2.webp',
    '/images/hero/lunch-3.webp',
    '/images/hero/lunch-4.webp',
    '/images/hero/lunch-5.webp',
    '/images/hero/toy-1.webp',
    '/images/hero/toy-2.webp',
    '/images/hero/toy-3.webp',
  ],
  heroSlidesMobileTabletJpg: [
    '/images/hero/lunch-1.jpg',
    '/images/hero/lunch-2.jpg',
    '/images/hero/lunch-3.jpg',
    '/images/hero/lunch-4.jpg',
    '/images/hero/lunch-5.jpg',
    '/images/hero/toy-1.jpg',
    '/images/hero/toy-2.jpg',
    '/images/hero/toy-3.jpg',
  ],
  pillarToys: '/products/toys/wooden-building-blocks/01.jpg',
  pillarLunchBox: '/products/lunch-box/hero-showcase/koi-koi-steel-lunch-box-blue.jpeg',
  homeBanner: '/products/lunch-box/hero-showcase/koi-koi-steel-lunch-box-blue.jpeg',
  serviceShipping: '/images/home5-info1.png',
  serviceSupport: '/images/home5-info2.png',
  serviceReturns: '/images/home5-info3.png',
  appStore: '/images/app1.png',
  playStore: '/images/app2.png',
  bankCard: '/images/Bank-card.png',
};
